pypgstac/pypgstac/pypgstac.py

Fix a bug in pypgstac where single quotes were not appropriately escaped.

Quoteinjsonfix

---

sql/004_search.sql

Fix for minor issue with the "greater than" operators to match revised "less than" operators.

Search operator typo fix

---

docker-compose.yml
scripts/test
sql/002_collections.sql
sql/003_items.sql
sql/004_search.sql
test/pgtap.sql
test/test.sh

Fixes PgTAP SQL tests and adds to the test script. (#22 )
Cleans out SQL that had been commented out.

PgTAP Tests

---

pypgstac/pypgstac/__init__.py
pypgstac/pypgstac/migrations/pgstac.0.2.8-0.2.9.sql
pypgstac/pypgstac/migrations/pgstac.0.2.9.sql
pypgstac/pyproject.toml
sql/999_version.sql

Bump version on main branch to 0.2.9.

Bump version to 0.2.9

---

pypgstac/pypgstac/migrate.py

If no migrations were necessary, the `run_migration` function had been exiting without closing the open `asyncpg.Connection`. This fixes that issue and wraps the entire function after opening the connection in a try/finally statement to ensure the connection gets closed.

Ensure connection is closed before exiting

---

CHANGELOG.md
pypgstac/pypgstac/__init__.py
pypgstac/pypgstac/migrations/pgstac.0.4.0-0.4.1.sql
pypgstac/pypgstac/migrations/pgstac.0.4.1.sql
pypgstac/pyproject.toml
sql/004_search.sql
sql/999_version.sql

- Bumps version to 0.4.1
- Adds changelog for v0.4.0 and v0.4.1 (fixes #73)
- Adds Fix for large queries in the query cache (fixes #71)
- Adds Fix to make sure that filter-lang always trumps default system filter settings (fixes #77)

Work v0.4.1

---

README.md

Hi @bitner , thanks for all the recent work on this! The `pgstac_settings` is a really useful change in 0.4.0 so I added it to the README so it would be obvious to others.

Added details for updating pgstac settings to readme

---

pypgstac/pyproject.toml

remove useless asyncio requirement

---

CHANGELOG.md
pypgstac/pypgstac/migrations/pgstac.0.6.0-0.6.1.sql
pypgstac/pypgstac/migrations/pgstac.0.6.1.sql
pypgstac/pypgstac/version.py
sql/001a_jsonutils.sql
sql/999_version.sql

- Fix issue where using equality operator against an array was only comparing the first element of the array

fix for to_text only returning first element of array

---

CHANGELOG.md
README.md
pypgstac/pypgstac/migrations/pgstac.0.6.1-0.6.2.sql
pypgstac/pypgstac/migrations/pgstac.0.6.2.sql
pypgstac/pypgstac/version.py
scripts/bin/stageversion
scripts/stageversion
sql/999_version.sql

Update version number, create migration scripts for 0.6.2
Also fix up the README and improve the scripts around staging versions.

Version 0.6.2

---

CHANGELOG.md
pypgstac/pypgstac/migrations/pgstac.0.6.5-0.6.6.sql
pypgstac/pypgstac/migrations/pgstac.0.6.6.sql
pypgstac/pypgstac/version.py
sql/001a_jsonutils.sql
sql/002b_cql.sql
sql/999_version.sql
test/basic/cql2_searches.sql
test/basic/cql2_searches.sql.out

Adds support for Array Operators (aequals, acontains, contained by, aoverlaps).

Add support for array operators

---

pypgstac/pypgstac/load.py

Fixes https://github.com/stac-utils/pgstac/issues/131

Keep pypgstac compatible with Python 3.7

---

CHANGELOG.md
pypgstac/pypgstac/migrations/pgstac.0.6.6-0.6.7.sql
pypgstac/pypgstac/migrations/pgstac.0.6.7.sql
pypgstac/pypgstac/version.py
sql/004_search.sql
sql/999_version.sql
test/pgtap.sql
test/pgtap/004_search.sql

This PR fixes https://github.com/stac-utils/pgstac/issues/140

Fix prev when reading first token_type=prev

---

CHANGELOG.md
pypgstac/pypgstac/migrations/pgstac.0.6.12-0.6.13.sql
pypgstac/pypgstac/migrations/pgstac.0.6.13.sql
pypgstac/pypgstac/version.py
sql/004_search.sql
sql/999_version.sql

Fix an issue with sorting and paging where in some circumstances the aggregation of items into a jsonb array changed the expected order.

fix for paging and sorting

---

CHANGELOG.md
src/pgstac/migrations/pgstac.0.7.7-0.7.8.sql
src/pgstac/migrations/pgstac.0.7.8.sql
src/pgstac/sql/004_search.sql
src/pgstac/sql/999_version.sql
src/pgstac/tests/basic/cql_searches.sql
src/pgstac/tests/basic/cql_searches.sql.out
src/pypgstac/pypgstac/version.py

- Fix issue with search_query not returning all fields on first use of a query. Fixes #182

fix for #182

---

CHANGELOG.md
Dockerfile
src/pgstac/migrations/pgstac.0.7.8-0.7.9.sql
src/pgstac/migrations/pgstac.0.7.9.sql
src/pgstac/sql/999_version.sql
src/pypgstac/pypgstac/version.py

Update docker to use postgis 3.3.3

update pg in docker to 3.3.3

---

docs/src/pgstac.md
src/pgstac/migrations/pgstac.0.8.1-unreleased.sql
src/pgstac/migrations/pgstac.unreleased.sql
src/pgstac/pgstac.sql
src/pgstac/sql/001_core.sql
src/pgstac/sql/002a_queryables.sql
src/pgstac/sql/002b_cql.sql
src/pgstac/sql/999_version.sql
src/pgstac/tests/pgtap.sql
src/pgstac/tests/pgtap/002a_queryables.sql
src/pypgstac/pyproject.toml
src/pypgstac/python/pypgstac/version.py

Enable mode to only allow search properties that are in the queryables table.

Enable strict mode for search

---

.github/workflows/release.yml

This PR add `arm64` docker image to be published 
ref https://github.com/developmentseed/eoAPI/issues/153#issuecomment-1781561265

add arm64 infrastructure for pgstac Docker images

---

src/pgstac/migrations/pgstac.0.8.4-0.8.5.sql
src/pgstac/migrations/pgstac.0.8.5.sql
src/pgstac/pgstac.sql
src/pgstac/sql/999_version.sql
src/pypgstac/pyproject.toml
src/pypgstac/python/pypgstac/version.py

stage v0.8.5 release

---

src/pgstac/sql/002b_cql.sql
src/pgstac/tests/pgtap/004_search.sql

Fixes https://github.com/stac-utils/pgstac/issues/249

Fix CQL2 parser for BETWEEN operator

---

CONTRIBUTING.md

- Small modification to adding test section
- Add a section on hydration and dehydration
Review the markdown file.

Small changes to contributing documentation

---

docker/pypgstac/Dockerfile

Fixes https://github.com/stac-utils/pgstac/issues/291

Fix migrations symlink

---

CHANGELOG.md
src/pgstac/migrations/pgstac.0.9.1-0.9.2.sql
src/pgstac/migrations/pgstac.0.9.2.sql
src/pgstac/pgstac.sql
src/pgstac/sql/999_version.sql
src/pypgstac/pyproject.toml
src/pypgstac/src/pypgstac/version.py

Stage migrations / changelog for v0.9.2 release

stage v0.9.2

---

.github/workflows/release.yml

following suggestions from https://github.com/docker/setup-qemu-action/issues/198

temporarily pin qemu action image
