stac-utils/pgstac

- pypgstac/pypgstac/pypgstac.py
This fixes an issue introduced in #18 with the usage of `isinstance` to check the return type of `smart_open.open`.
There was a check in place that was made under the assumption the return type would be consistent with what I was seeing in my development environment at time of coding; however in another instance I found this open returned an unexpected type for an
open file.
This change avoids having type checking interfere with runtime logic by assigning the open for file to `Any`, which skips further type checking.
> Fix issue with logic around type of object returned by smart_open

- sql/004_search.sql
- test/pgtap/004_search.sql
This PR does:
- add tests for collections search 
- make sure `collections` and not `collection` get translated to CQL.
closes #42
> Catch collections not collection in CQL filters

- CHANGELOG.md
- pypgstac/pypgstac/__init__.py
- pypgstac/pypgstac/migrations/pgstac.0.3.1-0.3.2.sql
- pypgstac/pypgstac/migrations/pgstac.0.3.2.sql
- pypgstac/pyproject.toml
- sql/999_version.sql
This PR updates the version to 0.3.2
- Ran `scripts/stageversion 0.3.2`
- Renamed the migration file from `.sql.staged` to `.sql`
- Updated CHANGELOG - I only added an entry for this release; there were previous releases without entries that I left a TODO for (cc @bitner)
Once this is in `main`, I'll tag main into a new release.
Note that this doesn't follow exactly the release process described in the README, but based on https://github.com/stac-utils/pgstac/pull/41 I'm not sure we were exactly following that process. The process as described would not update the version in `main` but instead increment things in the tag. Instead I'm making the changes in this PR, merging into main, and tagging from main. I think this results in the same effect, is similar to the process that was used for …
> Update to version 0.3.2

- Dockerfile
- README.md
- pypgstac/pypgstac/__init__.py
- pypgstac/pypgstac/migrate.py
- pypgstac/pypgstac/migrations/pgstac.0.3.4-0.3.5.sql
- pypgstac/pypgstac/migrations/pgstac.0.3.5.sql
- pypgstac/pyproject.toml
- scripts/bin/stageversion
- scripts/bin/stageversiondb
- sql/001_core.sql
- sql/001b_cursorutils.sql
- sql/003_items.sql
- sql/004_search.sql
- sql/999_version.sql
- test/pgtap/004_search.sql
- test/pgtap/006_tilesearch.sql
- Add constraints to each partition to help query planner leverage constraint exclusion
- Add constraints for collection_id and end_datetime
- Add functionality to triggers to drop constraints before load and readd them after a load
- Use explain with these constraints to get a list of partitions that would be hit by a query and use this list when looping through partitions
- Add metadata to searches table (fixes #53 superseded PR #54)
- Fixes for migration tagging (fixes #51 and #49)
- Adds knobs to control the use of context (instructions added in README on how to set)
- pgstac.context setting options
- 'on' always calculate the full count and report the context in the output
- 'auto' use the pgstac.context_estimated_count and pgstac.context_estimated_count variables to determine …
> Performance fixes

- CHANGELOG.md
- Dockerfile
- pypgstac/poetry.lock
- pypgstac/pyproject.toml
- scripts/update-poetry-lock
Update the poetry.lock file, and add as script that allows updating the poetry lock file through docker.
Also upgrades poetry in the Dockerfile.
Fixes #75
> Upgrade typer to 0.4.0

- CHANGELOG.md
- pypgstac/pypgstac/__init__.py
- pypgstac/pypgstac/migrations/pgstac.0.3.4-0.3.5.sql
- pypgstac/pypgstac/migrations/pgstac.0.4.1-0.4.2.sql
- pypgstac/pypgstac/migrations/pgstac.0.4.2.sql
- pypgstac/pyproject.toml
- sql/004_search.sql
- sql/999_version.sql
- test/pgtap.sql
- test/pgtap/004_search.sql
- Add fix to rename partitions causing error in 0.3.4->0.3.5 migration
- Adds support for [changes](https://github.com/radiantearth/stac-api-spec/pull/245/files) in timestamp/interval cql2 json syntax
> v0.4.2 - CQL2 and Migration Fixes

- CHANGELOG.md
- pypgstac/pypgstac/__init__.py
- pypgstac/pypgstac/migrations/pgstac.0.4.2-0.4.3.sql
- pypgstac/pypgstac/migrations/pgstac.0.4.3.sql
- pypgstac/pyproject.toml
- sql/004_search.sql
- sql/999_version.sql
- Fix for the equals optimization when querying the properties json. Prior to this, it would only kick in when the operator was "eq", now it will kick in for both "eq" and "=".
- Update version to 0.4.3
> fix for optimization when operator is '='

- CHANGELOG.md
- README.md
- pypgstac/poetry.lock
- pypgstac/pypgstac/__init__.py
- pypgstac/pypgstac/migrate.py
- pypgstac/pypgstac/migrations/pgstac.0.4.4-0.4.5.sql
- pypgstac/pypgstac/migrations/pgstac.0.4.5.sql
- pypgstac/pyproject.toml
- scripts/test
- sql/003_items.sql
- sql/999_version.sql
- test/pgtap.sql
- test/pgtap/004_search.sql
- Fixes support for using the intersects parameter at the base of a search (regression from changes in 0.4.4)
- Fixes issue where results for a search on id returned [None] rather than [] (regression from changes in 0.4.4)
- Changes requirement in README for PostgreSQL to 13+, the triggers used to main partitions are not available to be used on partitions prior to 13 (Fixes #90)
- Bump requirement for asyncpg to 0.25.0 (Fixes #82)
- Added more tests.
> Working v0.4.5

- pypgstac/pypgstac/db.py
- pypgstac/pypgstac/load.py
- pypgstac/pypgstac/migrate.py
This PR adds `.autocommit = True` to new connections from `PgstacDB`. 
I ran into an issue where long, multi-load ingests were holding locks for the duration of the entire ingest. There was a transaction was open the entire time the connection was open, and so the partition being ingested into was lockd the entire ingest. Using autocommit scoped the lock issues to a single scoped call to `load_items`.
Based on the [Hint at the bottom of these docs](https://www.psycopg.org/psycopg3/docs/basic/transactions.html?msclkid=496fe3b1d0d511eca8f7aae193c127a1#transaction-contexts), `autocommit` on the connections that are established in PgstacDB to avoid any transaction issues.
In addition, a scoped `logger` is used so that it's possible for client code to adjust logging levels of pypgstac …
> Add autocommit to connections

- pypgstac/pypgstac/load.py
- pypgstac/tests/test_load.py
The loader pop'd keys like `collection` off the item, then dehydrated the
item to be used as the 'content'. With `collection` removed prior to
dehydration, it was flagged with the "do-not-merge" marker because the
key is on the base_item. Instead, ensure that id, collection, and
geometry are not in `content` as they are stored on the table row and
shouldn't participate in hydration.
Additionally, bbox was previously a derived value at search runtime but
was recently changed to a returned value if it existed on the item.
However, during loading, the bbox was dropped so would never exist on
the persisted item.
> Ensure special keys are not in content when loaded

- CHANGELOG.md
- pypgstac/pypgstac/db.py
- pypgstac/pypgstac/load.py
This commit refactors the loader code to avoid unnecessary partition updates. Partition updates should be avoided when unnecessary as they can have a large performance impact for partitions containing many items.
> Avoid updating partitions table when unnecessary

- CHANGELOG.md
- pypgstac/pypgstac/load.py
In-place sort was being done on an ephemeral list. The lack of sort was causing itertools.group_by to make small groups as it streamed through the iterator, causing ingests to be slow for large sets of items with a mix of partitions. 
Seeing a significant performance increase for large item ingest with many partitions (weekly partitions on about 4 months of Sentinel 2, dropping 50K item group ingests from 1000s to 40s)
> Loader optimization: Fix incorrect in-place sort of chunks by partition

- pypgstac/pypgstac/load.py
- pypgstac/tests/test_load.py
Fixes https://github.com/stac-utils/pgstac/issues/123
> Add a check to the loader to make sure that the loader is compatible with the target database

- CHANGELOG.md
- pypgstac/pypgstac/migrations/pgstac.0.6.10.sql
- pypgstac/pypgstac/migrations/pgstac.0.6.9-0.6.10.sql
- pypgstac/pypgstac/version.py
- sql/002a_queryables.sql
- sql/999_version.sql
- test/pgtap/002a_queryables.sql
Currently, passing in a non-existent collection will return a valid queryable object.
> Don't return valid queryable object for invalid collection 

- pypgstac/setup.py
I am working on incorporating `pgstac` into a project and I had to downgrade to smart-open==4.2.0 so I thought I would try bumping the pinned version to the latest (6.2.*). Since I was in there already I bumped a few other less-outdated pinned versions, too. All of the tests are passing when I run `scripts/test` as described in the contributing guidelines!
Maybe there is a good reason smart-open is held back to version 4.2.* but in case there is not one, here is a PR!
> update pinned versions of several dependencies

- sql/002b_cql.sql
- test/pgtap/004_search.sql
- Prompted by https://github.com/stac-utils/stac-fastapi/issues/464
Adds support for empty strings in datetime intervals, e.g. `2023-02-02/`. Includes tests.
I'm opening this as a draft PR b/c I'm not sure of the correct process to propogate these changes to the actual files that get run (e.g.) when you do `scripts/test`. To test locally, I made a new version w/ my modifications. Does every PR get a new version?
> Allow empty strings in datetime intervals

- src/pypgstac/pypgstac/load.py
- src/pypgstac/pyproject.toml
- src/pypgstac/setup.py
- src/pypgstac/tests/test_load.py
The [previous library](https://setuptools.pypa.io/en/latest/pkg_resources.html) for parsing a version string relied on a particular version of setuptools (>=59) that wasn't a direct dependency of the project. As a result, different python environments would fail during loading. Switching to a library that can be pinned, a mostly drop-in replacement.
Existing version compatibility tests pass.
> Use library for version parsing

- CHANGELOG.md
- src/pgstac/migrations/pgstac.0.6.13-0.7.0.sql
- src/pgstac/migrations/pgstac.0.7.0.sql
- src/pgstac/migrations/pgstac.0.7.1-0.7.2.sql
- src/pgstac/migrations/pgstac.0.7.1.sql
- src/pgstac/migrations/pgstac.0.7.2.sql
- src/pgstac/sql/002a_queryables.sql
- src/pgstac/sql/003a_items.sql
- src/pgstac/sql/998_idempotent_post.sql
- src/pgstac/sql/999_version.sql
- src/pypgstac/pypgstac/load.py
- src/pypgstac/pypgstac/version.py
- src/pypgstac/tests/test_load.py
- Use version_parser for parsing versions in pypgstac
- Fix issue with dropping functions/procedures in 0.6.13->0.7.0 migrations
- Fix issue with CREATE OR REPLACE TRIGGER on PG 13
- Fix issue identifying duplicate indexes in maintain_partition_queries function
- Ensure that pgstac_read role has read permissions to all partitions
- Fix issue (and add tests) caused by bug in psycopg datetime types not being able to translate 'infinity', '-infinity'
> Bugfixrelease0.7.2

- CHANGELOG.md
- src/pgstac/sql/002_collections.sql
- src/pgstac/tests/pgtap/002a_queryables.sql
fixes #186 
test fails before:
test passes after:
> fix: return '[]' instead of NULL from all_collections when the table is empty

- docs/src/pgstac.md
- src/pgstac/migrations/pgstac.0.7.10-unreleased.sql
- src/pgstac/migrations/pgstac.unreleased.sql
- src/pgstac/sql/998_idempotent_post.sql
This default queryable was added in the early days of pgstac so that the field would be indexed by default if it was present in any items. However, now that the queryables table is used to generate content for `/queryables` stac endpoint in stac-fastapi, it is included in the queryable content for all collections (since there is no `collection_id`).
Removing this optimization fixes incorrect (and broken, since the $ref URL also has a typo) default behavior.
> Remove default eo:cloud_cover queryable

- .pre-commit-config.yaml
- CHANGELOG.md
- docker/pypgstac/bin/stageversion
- src/pgstac/migrations/pgstac.0.7.10-0.8.0.sql
- src/pgstac/migrations/pgstac.0.8.0.sql
- src/pgstac/pgstac.sql
- src/pgstac/sql/999_version.sql
- src/pypgstac/pyproject.toml
- src/pypgstac/python/pypgstac/version.py
- src/pypgstac/tests/hydration/test_dehydrate_pg.py
- src/pypgstac/tests/hydration/test_hydrate_pg.py
> fix bugs with staging version, update for v0.8.0 release

- .github/workflows/release.yml
- CHANGELOG.md
- src/pgstac/migrations/pgstac.0.8.0-0.8.1.sql
- src/pgstac/migrations/pgstac.0.8.1.sql
- src/pgstac/pgstac.sql
- src/pgstac/sql/999_version.sql
- src/pypgstac/pyproject.toml
- src/pypgstac/python/pypgstac/version.py
Fix a bug in CI for building/pushing docker images.
> Fixci releasev0.8.1

- src/pgstac/migrations/pgstac.0.8.1-unreleased.sql
- src/pgstac/migrations/pgstac.unreleased.sql
- src/pgstac/sql/002b_cql.sql
- src/pgstac/tests/pgtap.sql
- src/pgstac/tests/pgtap/002a_queryables.sql
> Make sure that only arguments that are properties are cheked

- CHANGELOG.md
- src/pgstac/migrations/pgstac.0.8.1-0.8.2.sql
- src/pgstac/migrations/pgstac.0.8.2.sql
- src/pgstac/pgstac.sql
- src/pgstac/sql/999_version.sql
- src/pypgstac/pyproject.toml
- src/pypgstac/python/pypgstac/version.py
- Add support functions and tests for Collection Search
- Add configuration parameter for base_url to be able to generate absolute links
- With this release, this is only used to create links for paging in collection_search
- Adds read only mode to allow use of pgstac on read replicas
- Note: Turning on romode disables any caching (particularly when context is turned on) and does not allow to store q query hash that can be used with geometry_search.
- Add option to pypgstac loader "--usequeue" that forces use of the query queue for the loading process
- Add "pypgstac runqueue" command to run any commands that are set in the query queue
- Fix bug with end_datetime constraint management leading to inability to add data outside of constraints
- Fix bugs dealing with table ownership to ensure …
> Release for v0.8.2

- src/pgstac/migrations/pgstac.0.8.2-unreleased.sql
- src/pgstac/migrations/pgstac.unreleased.sql
- src/pgstac/pgstac.sql
- src/pgstac/sql/003a_items.sql
- src/pgstac/sql/999_version.sql
- src/pgstac/tests/basic/crud_functions.sql
- src/pgstac/tests/basic/crud_functions.sql.out
- src/pypgstac/pyproject.toml
- src/pypgstac/python/pypgstac/version.py
Fixes a critical bug when using the ingest_staging_upsert table or the upsert_item/upsert_items functions to update records with existing data where the existing row would get deleted, but the new row would not get added.
Add tests for these functions.
> Fix for upsert_item and upsert_items functions

- CHANGELOG.md
- src/pgstac/migrations/pgstac.0.8.2-0.8.3.sql
- src/pgstac/migrations/pgstac.0.8.3.sql
- src/pgstac/pgstac.sql
- src/pgstac/sql/999_version.sql
- src/pypgstac/pyproject.toml
- src/pypgstac/python/pypgstac/version.py
Add Changelog and prep release for v0.8.3
> Release for v0.8.3

- .github/workflows/continuous-integration.yml
- .github/workflows/release.yml
- docker/pgstac/Dockerfile
- docker/pypgstac/bin/test
The docker image for pgstac has four targets.
- pgstacbase: This target is essentially the same as postgis/postgis with pgtap, plpgsql-check, and partman installed (which are used for testing/development, but not required for using pgstac), it is a base postgres/postgis image that is ready to install pgstac, but does not have it installed yet.
- pgstacbase-plrust: This is the pgstacbase image that also has PLRUST installed in preparation for future development (PLRUST is not used yet).
- pgstac: This target is the pgstacbase image with pgstac already installed at a specific version
- pgstac-rust: This target is the pgstacbase-plrust image with pgstac already installed at a specific version
CI ran into issues with building the pgstacbase-plrust and pgstac-plrust targets. This PR does three …
> Fix for CI docker builds.

- docs/src/pgstac.md
> Minor typo fix in docs

- src/pgstac/sql/002b_cql.sql
- src/pgstac/tests/pgtap/002a_queryables.sql
In strict mode, PgSTAC returns an error even though the `geometry` column is listed in the `queryables` table:
```
Term geometry is not found in queryables.
```
> Enable querying of the geometry column

- docs/src/pgstac.md
Hi all! 
This PR is correcting what I _think_ is a tiny typo in the docs: the filter languages are either CQL JSON or CQL2 JSON, not CQL JSON2. This also matches the allowed levels of the variable.
> Fix documentation typo (cql-json2 -> cql2-json)

- src/pgstac/migrations/pgstac.0.8.5-unreleased.sql
- src/pgstac/migrations/pgstac.unreleased.sql
- src/pgstac/pgstac.sql
- src/pgstac/sql/000_idempotent_pre.sql
- src/pgstac/sql/002b_cql.sql
- src/pgstac/sql/998_idempotent_post.sql
- src/pgstac/sql/999_version.sql
- src/pgstac/tests/pgtap.sql
- src/pgstac/tests/pgtap/004_search.sql
- src/pypgstac/pyproject.toml
- src/pypgstac/python/pypgstac/version.py
Adds support for casei and accenti operators. Fixes #237. Does not remove existing upper, lower functions or the ilike operator to not break backwards compatibility.
> Add support for casei and accenti

- CHANGELOG.md
- docs/src/pypgstac.md
I updated `docs/src/pypgstac.md` with information on the trigger to update collection extent. 
I re-worded the discussion in #247.
Closes #247.
Run `mkdocs serve` and visualize the integrated changes.
> Add information on automated collection extents trigger

- src/pypgstac/src/lib.rs
- src/pypgstac/tests/hydration/test_hydrate.py
For https://github.com/stac-utils/stac-fastapi-pgstac/pull/107
> Allow `None` in rehydration

- CHANGELOG.md
changes for 0.8.5 was added within the 0.9.0 block. this PR fixes this!
> fix changelog and add 0.8.5 changes

- docker/pypgstac/Dockerfile
- src/pypgstac/pyproject.toml
Relaxes dependency version for smar-open (fixes https://github.com/stac-utils/pgstac/issues/273)
Use uv pip in the pypgstac docker image to get requirements from pyproject.toml and to install requirements.
> relax smart-open, use uv for docker

- CHANGELOG.md
- src/pgstac/migrations/pgstac.0.9.0-0.9.1.sql
- src/pgstac/migrations/pgstac.0.9.1.sql
- src/pgstac/pgstac.sql
- src/pgstac/sql/999_version.sql
- src/pypgstac/pyproject.toml
- src/pypgstac/python/pypgstac/version.py
Stage recent changes for release.
- Fixed double nested extent when using trigger based update collection extent. (Fixes #274)
- Fix time formatting (Fixes #275)
- Relaxes smart-open dependency check (Fixes #273)
- Switch to uv for docker image
> stage version 0.9.1

- docs/src/pgstac.md
Some cloud providers (ex. azure) need extra steps to allow the btree_gist extension in postgres database servers.
> Add btree_gist dependency in docs

- CHANGELOG.md
- src/pgstac/migrations/pgstac.0.9.1-unreleased.sql
- src/pgstac/migrations/pgstac.unreleased.sql
- src/pgstac/pgstac.sql
- src/pgstac/sql/004_search.sql
- src/pgstac/sql/999_version.sql
- src/pgstac/tests/basic/free_text.sql
- src/pgstac/tests/basic/free_text.sql.out
- src/pypgstac/pyproject.toml
- src/pypgstac/python/pypgstac/version.py
This adds the `q` parameter for free-text search. It will be pretty slow for item-level search because it has to compute the `tsvectors` on-the-fly, but it works great for collection-level search where the number of records should be limited.
Resolves #293 (for collection-level search at least)
> add q parameter for free-text search

- src/pgstac/sql/004_search.sql
It fixes the following issue:
```
postgis=> SELECT search('{}');
NOTICE:  SEARCH: {}
NOTICE:  FILTER: <NULL>
ERROR:  cannot execute SELECT FOR UPDATE in a read-only transaction
CONTEXT:  SQL statement "SELECT *         FROM search_wheres WHERE md5(_where)=inwhere_hash FOR UPDATE"
PL/pgSQL function where_stats(text,boolean,jsonb) line 57 at SQL statement
PL/pgSQL function search(jsonb) line 65 at assignment
```
I proposed the test in another PR: https://github.com/stac-utils/pgstac/pull/297
> Allow read-only replicas work even when the context extension is enabled

- CHANGELOG.md
- src/pypgstac/python/pypgstac/db.py
ref https://github.com/psycopg/psycopg/pull/659
> avoid future breaking change in psycopg ConnectionPool

- src/pypgstac/python/pypgstac/db.py
- src/pypgstac/python/pypgstac/migrate.py
ref: https://github.com/stac-utils/stac-fastapi-pgstac/issues/147
When using beta version of Postgres (e.g `17beta3`) the current code using `server_version` would fail. Using `server_version_num` overcome this and avoid having to parse the version number
> switch from server_version to server_version_num

- src/pgstac/sql/002a_queryables.sql
From the [docs](https://www.postgresql.org/docs/current/plpgsql-errors-and-messages.html):
> Inside the format string, % is replaced by the string representation of the next optional argument's value
> Fix string interpolation

- .github/workflows/continuous-integration.yml
Rather than adding the `if: changes` logic at the job-level, add it at the actual build and push step.
> always run tests even if docker images don't rebuild

- .github/workflows/continuous-integration.yml
- src/pypgstac/pyproject.toml
@bitner I'm of the `>=` school. If a upstream breaks, we can just ceil (CI should catch the break). I've added a test to CI to test with both our min version and whatever pip pulls in on a normal install.
- Closes #341
> deps: relax

- .gitignore
- CHANGELOG.md
- docs/src/pypgstac.md
- src/pypgstac/examples/load_queryables_example.py
- src/pypgstac/examples/sample_queryables.json
- src/pypgstac/src/pypgstac/pypgstac.py
- src/pypgstac/tests/data-files/queryables/test_queryables.json
- src/pypgstac/tests/test_queryables.py
This PR adds a new `load_queryables` function to pypgstac that allows loading queryables from a JSON file. Queryables are a mechanism that allows clients to discover what terms are available for use when writing filter expressions in a STAC API.
The new function:
- Takes a JSON file path and optional collection IDs as input
- Parses the queryables definition from the JSON file
- Determines the appropriate property wrapper based on the type of each property
- Inserts the queryables into the database
- Handles conflicts with existing queryables by deleting and reinserting them to ensure triggers are executed
- Added `load_queryables` method to the `PgstacCLI` class in `src/pypgstac/src/pypgstac/pypgstac.py`
- Updated documentation in `docs/src/pypgstac.md` to include information about the …
> Add `load_queryables` function to pypgstac

- src/pypgstac/pyproject.toml
Fixes https://github.com/stac-utils/pgstac/issues/328. The [fix](https://github.com/google/python-fire/pull/447) was included in the 0.7.0 release.
> Udpate fire to 0.7.0

- CHANGELOG.md
- docker/pypgstac/bin/makemigration
- src/pgstac/migrations/pgstac.0.8.6-0.9.0.sql
- src/pgstac/migrations/pgstac.0.8.6.sql
Here are the steps I took to add the migration file:
1. copied pgstac.0.8.6.sql from v0.8.6 tag into this branch
2. ran `scripts/runinpypgstac --build --cpfiles makemigration -f 0.8.6 -t 0.9.0`
resolves #335
I also modified the `makeversion` script to dynamically set the version from the `$TO` arg because when I ran `makemigration -f 0.8.6 -t 0.9.0` initially the `999_version.sql` file got tacked onto the end and mistakenly set the version to 0.9.5 which caused a failure in the migration when I tried running it.
> Fix: add missing 0.8.6-0.9.0 migration script

- docs/src/pypgstac.md
Provide detailed instructions for initializing an empty PgSTAC database.
> Enhance migration bootstrap documentation
